#!/bin/bash
# Generates fresh RSA keypairs, saves them to .secrets/, and prints them.
# Run locally once. Never commit the .secrets/ directory.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${REPO_ROOT}/.secrets"
mkdir -p "${OUT_DIR}"
chmod 700 "${OUT_DIR}"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

echo "Generating Keycloak realm RSA-2048 signing key..."
openssl genrsa -out "$TMP/realm.pem" 2048 2>/dev/null
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt \
  -in "$TMP/realm.pem" -out "$TMP/realm-pkcs8.pem"
openssl req -new -x509 -key "$TMP/realm.pem" -out "$TMP/realm-cert.pem" \
  -days 3650 -subj "/CN=zeroverify-realm" 2>/dev/null

REALM_KEY=$(grep -v '^-----' "$TMP/realm-pkcs8.pem" | tr -d '\n')
REALM_CERT=$(grep -v '^-----' "$TMP/realm-cert.pem" | tr -d '\n')

echo "Generating Mock IdP RSA-2048 signing key..."
openssl genrsa -out "$TMP/idp.pem" 2048 2>/dev/null
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt \
  -in "$TMP/idp.pem" -out "$TMP/idp-pkcs8.pem"
openssl req -new -x509 -key "$TMP/idp.pem" -out "$TMP/idp-cert.pem" \
  -days 3650 -subj "/CN=mock-idp.zeroverify.net" 2>/dev/null

IDP_KEY=$(grep -v '^-----' "$TMP/idp-pkcs8.pem" | tr -d '\n')
IDP_CERT=$(grep -v '^-----' "$TMP/idp-cert.pem" | tr -d '\n')

# Save to .secrets/ (one file per secret)
printf '%s' "$REALM_KEY"  > "${OUT_DIR}/KC_REALM_RSA_PRIVATE_KEY.txt"
printf '%s' "$REALM_CERT" > "${OUT_DIR}/KC_REALM_RSA_CERT.txt"
printf '%s' "$IDP_CERT"   > "${OUT_DIR}/MOCK_IDP_CERT.txt"
printf '%s' "$IDP_KEY"    > "${OUT_DIR}/IDP_PRIVATE_KEY.txt"
printf '%s' "$IDP_CERT"   > "${OUT_DIR}/IDP_CERT.txt"
chmod 600 "${OUT_DIR}"/*.txt

echo ""
echo "========================================================"
echo "  Railway → keycloak service                            "
echo "  Saved to: ${OUT_DIR}/KC_REALM_RSA_PRIVATE_KEY.txt    "
echo "========================================================"
echo "KC_REALM_RSA_PRIVATE_KEY=${REALM_KEY}"
echo ""
echo "========================================================"
echo "  Railway → keycloak service                            "
echo "  Saved to: ${OUT_DIR}/KC_REALM_RSA_CERT.txt           "
echo "========================================================"
echo "KC_REALM_RSA_CERT=${REALM_CERT}"
echo ""
echo "========================================================"
echo "  Railway → keycloak service (set when mock IdP ready)  "
echo "  Saved to: ${OUT_DIR}/MOCK_IDP_CERT.txt               "
echo "========================================================"
echo "MOCK_IDP_CERT=${IDP_CERT}"
echo ""
echo "========================================================"
echo "  mock-idp repo secrets                                  "
echo "  Saved to: ${OUT_DIR}/IDP_PRIVATE_KEY.txt             "
echo "========================================================"
echo "IDP_PRIVATE_KEY=${IDP_KEY}"
echo ""
echo "========================================================"
echo "  mock-idp repo secrets                                  "
echo "  Saved to: ${OUT_DIR}/IDP_CERT.txt                    "
echo "========================================================"
echo "IDP_CERT=${IDP_CERT}"
echo ""
echo "========================================================"
echo "  Set manually — not generated by this script           "
echo "========================================================"
echo "KEYCLOAK_ADMIN=admin"
echo "KEYCLOAK_ADMIN_PASSWORD=<choose a strong password>  →  Railway: keycloak service"
echo "RAILWAY_TOKEN=<from Railway → Account → Tokens>      →  GitHub: repository secrets"
echo ""
echo "Delete .secrets/ once everything is stored in your password manager."
